name = "ime-manager"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ime_db"
database_id = "8af0eab3-694a-4afc-ad36-7c4eebbc89ce"
